name: Bug Report
description: Report a bug or unexpected behavior in Atabeh
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. The more detail you provide, the easier it will be for us to track down and fix the problem.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of what went wrong
      placeholder: Tell us what you experienced
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear description of what you thought would happen
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Tell us how to recreate the issue
      placeholder: |
        1. Start Atabeh with config...
        2. Run test on...
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Atabeh Version
      description: Which version of Atabeh are you using?
      placeholder: "e.g., 0.1.0, commit abc123"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running Atabeh on?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: If running from source, which Go version?
      placeholder: "e.g., go1.21.5"

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste any relevant log output, error messages, or stack traces
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration details
      description: If relevant, share configuration details (remove any sensitive information)
      placeholder: |
        Config source type: subscription link
        Parser used: vmess
        Number of configs: 50

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might be relevant
      placeholder: |
        This started happening after...
        It only occurs when...
        I've tried these workarounds...

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission checks
      description: Please verify you've done the following before submitting
      options:
        - label: I've searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I've removed any sensitive information from this report
          required: true
        - label: I can reproduce this issue consistently
          required: false